export enum GenderEnum {
    TERROR = "TERROR",
    COMEDY = "COMEDIA",
    DRAMA = "DRAMA",
    ROMANCE = "ROMANCE",
    ACTION = "ACCION",
    SCIENCE_FICTION = "CIENCIA FICCION",
    HORROR = "HORROR",
    THRILLER = "THRILLER",
    CRIME = "CRIMENES",
    MYSTERY = "MISTERIO",
    DOCUMENTARY = "DOCUMENTAL",
    BIOGRAPHY = "BIOGRAFIA",
    HISTORY = "HISTORIA",
    WAR = "GUERRA",
    WESTERN = "OESTE",
    FAMILY = "FAMILIA",
    ADVENTURE = "AVENTURA",
    ANIMATION = "ANIMACION",
    MUSIC = "MUSICA",
    SPORT = "DEPORTES",
    NEWS = "NOTICIAS",
    REALITY = "REALIDAD",
    GAME_SHOW = "JUEGOS",
    TALK_SHOW = "CHARLAS",
}

export const listAllGenders = [
    GenderEnum.TERROR,
    GenderEnum.COMEDY,
    GenderEnum.DRAMA,
    GenderEnum.ROMANCE,
    GenderEnum.ACTION,
    GenderEnum.SCIENCE_FICTION,
    GenderEnum.HORROR,
    GenderEnum.THRILLER,
    GenderEnum.CRIME,
    GenderEnum.MYSTERY,
    GenderEnum.DOCUMENTARY,
    GenderEnum.BIOGRAPHY,
    GenderEnum.HISTORY,
    GenderEnum.WAR,
    GenderEnum.WESTERN,
    GenderEnum.FAMILY,
    GenderEnum.ADVENTURE,
    GenderEnum.ANIMATION,
    GenderEnum.MUSIC,
    GenderEnum.SPORT,
    GenderEnum.NEWS,
    GenderEnum.REALITY,
    GenderEnum.GAME_SHOW,
    GenderEnum.TALK_SHOW,
]